#!/usr/bin/env bash
# install_security_layer.sh
# ─────────────────────────────────────────────────────────────────────────────
# Copies every generated security file into its final location inside the
# attendance_backend project.
#
# Run from the directory that CONTAINS attendance_backend/:
#   bash install_security_layer.sh
#
# The script:
#   1. Creates all new directories.
#   2. Writes __init__.py stubs to every new package directory.
#   3. Backs up the three API files it overwrites.
#   4. Copies secured versions of the three API files into place.
#   5. Copies new middleware, decorator, service, and util files.
#   6. Prints a summary of every action taken.
#
# No existing files other than the three API files are overwritten without
# first creating a .bak backup next to them.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SRC="attendance_backend"          # generated files live here already
DST="attendance_backend"          # target — same tree in this case

GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
NC="\033[0m"

ok()   { echo -e "${GREEN}✓${NC}  $*"; }
warn() { echo -e "${YELLOW}⚠${NC}  $*"; }
err()  { echo -e "${RED}✗${NC}  $*"; exit 1; }

header() {
  echo ""
  echo -e "${GREEN}══════════════════════════════════════════${NC}"
  echo -e "${GREEN}  $*${NC}"
  echo -e "${GREEN}══════════════════════════════════════════${NC}"
}

# ── 1. Create directories ──────────────────────────────────────────────────────
header "Creating package directories"

DIRS=(
  "$DST/middleware"
  "$DST/decorators"
  "$DST/services"
  "$DST/utils"
  "$DST/api"
)
for d in "${DIRS[@]}"; do
  mkdir -p "$d"
  ok "mkdir -p $d"
done


# ── 2. __init__.py stubs ───────────────────────────────────────────────────────
header "Creating __init__.py stubs"

INIT_DIRS=(
  "$DST/middleware"
  "$DST/decorators"
  "$DST/services"
  "$DST/utils"
  "$DST/api"
)
for d in "${INIT_DIRS[@]}"; do
  INIT="$d/__init__.py"
  if [ ! -f "$INIT" ]; then
    echo '"""Package init — auto-generated by install_security_layer.sh"""' > "$INIT"
    ok "created $INIT"
  else
    warn "exists  $INIT (skipped)"
  fi
done


# ── 3. Back up API files that will be overwritten ──────────────────────────────
header "Backing up original API files"

backup() {
  local f="$1"
  if [ -f "$f" ]; then
    cp "$f" "${f%.py}.bak.py"
    ok "backed up $f → ${f%.py}.bak.py"
  else
    warn "$f does not exist yet — no backup needed"
  fi
}

backup "$DST/api/admin.py"
backup "$DST/api/teacher.py"
backup "$DST/api/student.py"
backup "$DST/api/attendance.py"
backup "$DST/main.py"


# ── 4. Install secured API files ───────────────────────────────────────────────
header "Installing secured API files"

install_file() {
  local src="$1"
  local dst="$2"
  if [ -f "$src" ]; then
    cp "$src" "$dst"
    ok "installed $src → $dst"
  else
    err "Source file not found: $src"
  fi
}

install_file "$SRC/api/admin_secured.py"      "$DST/api/admin.py"
install_file "$SRC/api/teacher_secured.py"    "$DST/api/teacher.py"
install_file "$SRC/api/student_secured.py"    "$DST/api/student.py"
install_file "$SRC/api/attendance_secured.py" "$DST/api/attendance.py"


# ── 5. Install new files ───────────────────────────────────────────────────────
header "Installing new security-layer files"

# main.py
install_file "$SRC/main.py" "$DST/main.py"

# auth API + audit API
install_file "$SRC/api/auth.py"  "$DST/api/auth.py"
install_file "$SRC/api/audit.py" "$DST/api/audit.py"

# Middleware
install_file "$SRC/middleware/auth_middleware.py"       "$DST/middleware/auth_middleware.py"
install_file "$SRC/middleware/permission_middleware.py" "$DST/middleware/permission_middleware.py"
install_file "$SRC/middleware/audit_middleware.py"      "$DST/middleware/audit_middleware.py"

# Decorators
install_file "$SRC/decorators/auth_decorators.py" "$DST/decorators/auth_decorators.py"

# Services
install_file "$SRC/services/auth_service.py"  "$DST/services/auth_service.py"
install_file "$SRC/services/audit_service.py" "$DST/services/audit_service.py"

# Utils
install_file "$SRC/utils/rate_limiter.py" "$DST/utils/rate_limiter.py"


# ── 6. Clean up staging artefacts ─────────────────────────────────────────────
header "Cleaning up staging files"

STAGING=(
  "$DST/api/admin_secured.py"
  "$DST/api/teacher_secured.py"
  "$DST/api/student_secured.py"
  "$DST/api/attendance_secured.py"
  "$DST/apply_security_patch.py"
)
for f in "${STAGING[@]}"; do
  if [ -f "$f" ]; then
    rm "$f"
    ok "removed $f"
  fi
done


# ── 7. Summary ────────────────────────────────────────────────────────────────
header "Installation complete"

echo ""
echo "Files installed / updated:"
echo "  attendance_backend/main.py                              (wires middleware)"
echo "  attendance_backend/api/auth.py                          (NEW — login endpoint)"
echo "  attendance_backend/api/audit.py                         (NEW — audit log API)"
echo "  attendance_backend/api/admin.py                         (require_admin on all endpoints)"
echo "  attendance_backend/api/teacher.py                       (require_teacher + section auth)"
echo "  attendance_backend/api/student.py                       (require_student + own-data)"
echo "  attendance_backend/api/attendance.py                    (role checks per endpoint)"
echo "  attendance_backend/middleware/auth_middleware.py         (NEW)"
echo "  attendance_backend/middleware/permission_middleware.py   (NEW)"
echo "  attendance_backend/middleware/audit_middleware.py        (NEW)"
echo "  attendance_backend/decorators/auth_decorators.py        (NEW)"
echo "  attendance_backend/services/auth_service.py             (NEW)"
echo "  attendance_backend/services/audit_service.py            (NEW)"
echo "  attendance_backend/utils/rate_limiter.py                (NEW)"
echo ""
echo "Backups of overwritten files are saved as *.bak.py next to the originals."
echo ""
echo -e "${GREEN}Next step: add JWT_SECRET to your .env, then restart uvicorn.${NC}"
echo ""
